# Generated by Django 2.0.5 on 2018-05-24 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('details', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('space', models.CharField(default='Hall', max_length=255, verbose_name='space')),
                ('is_public', models.BooleanField(default=True, verbose_name='public?')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('getin_time', models.TimeField(blank=True, null=True, verbose_name='get-in time')),
                ('setup_time', models.TimeField(blank=True, null=True, verbose_name='set-up time')),
                ('open_time', models.TimeField(default='20:00:00', verbose_name='opening time')),
                ('end_time', models.TimeField(default='23:59:59', verbose_name='closing time')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='weekly event?')),
                ('adv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='advance price')),
                ('door_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='door price')),
                ('conc_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='concession price')),
                ('ticket_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='ticket link')),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TOTAL fee')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='advance fee')),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='balance due')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='deposit received')),
                ('balance_date', models.DateField(blank=True, null=True, verbose_name='balance due date')),
                ('hirer_name', models.CharField(default='me', max_length=255, verbose_name='contact')),
                ('hirer_address', models.CharField(default='', max_length=255, verbose_name='contact')),
                ('hirer_postcode', models.CharField(default='', max_length=255, verbose_name='contact')),
                ('hirer_email', models.CharField(default='', max_length=255, verbose_name='contact')),
                ('hirer_phone', models.IntegerField(blank=True, default='0123 456 789', verbose_name='phone')),
                ('hirer_mobile', models.IntegerField(blank=True, default='0123 456 789', verbose_name='mobile')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_updated', models.DateTimeField(blank=True, null=True, verbose_name='date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_date'],
            },
        ),
    ]
