# Generated by Django 2.0.5 on 2018-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20180524_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hirer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hirer_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hirer_postcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='postcode'),
        ),
    ]
