# Generated by Django 2.0.5 on 2018-05-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180526_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='realm_slug',
            new_name='event_slug',
        ),
    ]
