# Generated by Django 2.0.5 on 2018-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20180526_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='percentage of door'),
        ),
    ]
