# Generated by Django 2.0.5 on 2018-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_event_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='00:00:00', verbose_name='closing time'),
        ),
    ]
